task_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^.*$', RedirectView.as_view(url="/tasks/", permanent=False)),
]

tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/add/$', views.add_task, name="add"),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/list/$', views.list_task, name="list"),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/export/$', views.export_task, name="export"),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/total-hours/$', views.calc_total_hours, name="total-hours"),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/owner-hours/$', views.calc_owner_hours, name="owner-hours"),
    url(r'^(?P<iteration>[a-zA-Z0-9]+)/tasks-by-owner/$', views.group_tasks_by_owner, name="tasks-by-owner"),
    url(r'^update/$', views.update, name="update"),
    url(r'^freeze/$', views.freeze, name="freeze"),
    url(r'^need-review/$', views.need_review, name="need-review"),
    url(r'^ordering-update/$', views.update_ordering, name="update-ordering"),
    url(r'^import/$', views.batch_import, name="import"),
    url(r'^import/confirm/$', views.confirm_import, name="import-confirm"),
]

tasks/models.py
from django.db import models


class Member(models.Model):
    name = models.CharField(max_length=64)

    def __unicode__(self):
        return self.name


class Iteration(models.Model):
    name = models.CharField(max_length=64)
    date_created = models.DateTimeField(auto_now_add=True)
    planned_time = models.FloatField(default=0)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('tasks:list', args=[self.name])

    def __unicode__(self):
        return 'Iteration - %s' % self.name

    class Meta:
        ordering = ['-date_created']


class Task(models.Model):
    iteration = models.ForeignKey(Iteration)
    ticket_id = models.IntegerField(unique=True)
    summary = models.CharField(max_length=512)
    owner = models.ForeignKey(Member, null=True, blank=True)
    estimated_hours = models.FloatField(default=0)
    frozen = models.BooleanField(default=False)
    need_review = models.BooleanField(default=False)
    review_time = models.FloatField(default=0)
    ordering = models.IntegerField(default=0)

    def __unicode__(self):
        return '#%s' % self.ticket_id

    class Meta:
        ordering = ['ordering']

tasks/forms.py
import re
from StringIO import StringIO

from django import forms
from django.core import validators
from django.db.models import F
from django.forms.utils import ErrorList

from .models import Task

task_info_cpt = re.compile(r'(^#\d+)(.*$)', re.I)


class TaskConvertForm(forms.Form):
    iteration = forms.CharField(validators=[validators.RegexValidator(regex=r"[a-zA-Z0-9]+")])
    planned_time = forms.FloatField(required=False)
    tasks = forms.CharField(label=u'Tasks Information', widget=forms.Textarea)

    def clean_tasks(self):
        tasks = self.cleaned_data.get('tasks')
        task_list = []
        if tasks:
            for line in StringIO(tasks):
                line = line.strip()
                task_info = task_info_cpt.findall(line)
                if task_info:
                    task_list.extend(task_info)
        if task_list:
            return task_list
        else:
            raise forms.ValidationError('Invalid Tasks Information.')


class AddTaskForm(forms.ModelForm):
    def __init__(
            self, data=None, files=None, auto_id='id_%s', prefix=None, initial=None, error_class=ErrorList,
            label_suffix=None, empty_permitted=False, instance=None):
        if data is not None:
            ticket_id = data.get('ticket_id')
            if ticket_id:
                task = Task.objects.filter(ticket_id=ticket_id).first()
                if task is not None:
                    instance = task
        super(AddTaskForm, self).__init__(
            data, files, auto_id, prefix, initial, error_class, label_suffix, empty_permitted, instance)

    class Meta:
        model = Task
        exclude = ()
        widgets = {
            'iteration': forms.HiddenInput,
        }

    def save(self, commit=True):
        task = super(AddTaskForm, self).save(commit=commit)
        ordering = task.ordering
        base_query = Task.objects.filter(iteration=task.iteration)
        if task.id is not None:
            base_query = base_query.exclude(id=task.id)
        if base_query.filter(ordering=ordering).exists():
            base_query.filter(ordering__gte=ordering).update(ordering=F('ordering')+1)
        return task

tasks/views.py
from collections import defaultdict
import json


from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http.response import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST

from .forms import TaskConvertForm, AddTaskForm
from .models import Iteration, Task, Member
from .utils import update_task_ordering


def index(request):
    iterations = Iteration.objects.select_related().all()
    ctx = {
        'iterations': iterations,
    }
    return render(request, 'index.html', ctx)


def batch_import(request):
    ctx = {}
    if request.POST:
        form = TaskConvertForm(request.POST)
        if form.is_valid():
            task_list = form.cleaned_data['tasks']
            ctx['task_list'] = task_list
    else:
        form = TaskConvertForm()
    ctx['form'] = form
    return render(request, 'import.html', ctx)


def confirm_import(request):
    if request.POST:
        data = request.POST

        tasks_count = int(data.get('tasks_count'))
        iteration_name = data.get('iteration', "").strip()
        planned_time = data.get('planned_time')

        if not iteration_name:
            raise
        iteration, __ = Iteration.objects.get_or_create(name=iteration_name)
        iteration.planned_time = planned_time
        iteration.save()

        for i in range(tasks_count):
            number = data.get('task_number_%d' % i)
            if not number:
                continue
            summary = data.get('task_summary_%d' % i, "")
            number = number.strip().strip('#')
            summary = summary.strip()
            Task.objects.update_or_create(
                ticket_id=number, defaults={'summary': summary, 'iteration': iteration, 'ordering': i})

        messages.info(request, 'Import Successfully!')
        return redirect(iteration)


def add_task(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)
    if request.method == 'GET':
        form = AddTaskForm(initial={"iteration": iteration})
    else:
        form = AddTaskForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "Add Successfully!")
            return redirect(iteration)
    return render(request, 'add.html', {'form': form})


def list_task(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)
    owner_mapping = dict(Member.objects.values_list('id', 'name'))
    owner_mapping.update({
        '': '-----',
        'selected': ''
    })
    ctx = {
        'iteration': iteration,
        'owner_select': json.dumps(owner_mapping),
    }
    return render(request, 'list.html', ctx)


def export_task(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)

    line_formatter = "%(ticket_id)s\t%(summary)s\t%(estimated_hours)s"
    if request.GET.get('with_owner'):
        line_formatter += "\t%(owner__name)s"
    query_args = ('ticket_id', 'summary', 'estimated_hours', 'owner__name', 'need_review', 'review_time')
    task_info_list = iteration.task_set.filter(frozen=False).exclude(estimated_hours=0).values(*query_args)
    lines = []
    total_hours = 0
    for task_info in task_info_list:
        _need_review = task_info.pop('need_review', False)
        if _need_review:
            task_info['estimated_hours'] += task_info['review_time']
        total_hours += task_info['estimated_hours']
        lines.append(line_formatter % task_info)
    lines.append('Total Hours: %s' % total_hours)
    result = "\r\n".join(lines)
    response = HttpResponse(result, content_type="text/html")
    response['Content-Disposition'] = 'attachment; filename="%s.txt"' % iteration.name

    return response


def calc_total_hours(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)
    total_hours = 0
    for task in iteration.task_set.filter(frozen=False):
        estimated_hours = task.estimated_hours
        total_hours += estimated_hours
        if task.need_review:
            total_hours += task.review_time
    return HttpResponse(total_hours)


def calc_owner_hours(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)
    owner_hours = defaultdict(int)
    for task in iteration.task_set.filter(frozen=False):
        owner = task.owner.name if task.owner else 'left'
        estimated_hours = task.estimated_hours
        owner_hours[owner] += estimated_hours
        if task.need_review:
            owner_hours[owner] += task.review_time
    return JsonResponse(owner_hours)


def group_tasks_by_owner(request, iteration):
    iteration = get_object_or_404(Iteration, name=iteration)
    owner_tasks = defaultdict(list)
    all_tasks = iteration.task_set.filter(frozen=False).exclude(estimated_hours=0).values_list(
        'owner__name', 'ticket_id', 'need_review')
    for owner, ticket_id, need_review in all_tasks:
        owner_tasks[owner].append((ticket_id, need_review))
    return JsonResponse(owner_tasks)


@require_POST
def update(request):
    data = request.POST
    task = get_object_or_404(Task, id=data.get('task_id'))
    attr = data.get('name')
    value = data.get('value')
    setattr(task, attr, value)
    task.save()
    if attr == "owner_id":
        value = task.owner.name
    else:
        value = getattr(task, attr)
    return HttpResponse(value)


def update_ordering(request):
    data = request.GET
    task = get_object_or_404(Task, id=data.get('task_id'))
    ordering = data.get('ordering')
    ordering = int(ordering)
    update_task_ordering(task, ordering)
    return HttpResponse('OK')


def freeze(request):
    data = request.GET
    task = get_object_or_404(Task, id=data.get('task_id'))
    frozen = data.get('frozen') == 'true'
    task.frozen = frozen
    task.save()
    return HttpResponse('OK')


def need_review(request):
    data = request.GET
    task = get_object_or_404(Task, id=data.get('task_id'))
    _need_review = data.get('need_review') == 'true'
    task.need_review = _need_review
    task.save()
    return HttpResponse('OK')

tasks/templates/add.html
{% extends "base.html" %}

{% block h1 %}
  Task Manger - Add Task
{% endblock %}

{% block content %}
  <form action="" method="post">
    {{ form.as_p }}
    <button type="submit">Add Task</button>
  </form>
{% endblock %}

tasks/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %}</title>

  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/sweetalert.css" rel="stylesheet">
  <style>
    body {padding-top: 50px;}
  </style>
  {% block css %}{% endblock %}
</head>
<body>
  {% block message %}
    {% for message in messages %}
      <div class="alert alert-success" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endblock %}

  {% block nav %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Task Manager</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li role="presentation"><a href="{% url 'tasks:index' %}">Task List</a></li>
            <li role="presentation"><a href="{% url 'tasks:import' %}">Import Tasks</a></li>
          </ul>
        </div>
      </div>
    </nav>
  {% endblock %}


  <div class="container-fluid">
    <div class="page-header">
      <h1>
        {% block h1 %}{% endblock %}
      </h1>
    </div>
  </div>

  {% block content %}{% endblock %}

  <script src="/static/js/lib/jquery-2.1.4.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="/static/js/sweetalert.min.js"></script>
  <script src="/static/js/lib/jquery-ui.min.js"></script>
  <script src="/static/js/lib/jquery.cookie.js"></script>
  <script src="/static/js/lib/jquery.jeditable.mini.js"></script>
  <script>
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
            }
        }
    });
  </script>
  {% block js %}{% endblock %}
</body>
</html>

tasks/templates/import.html
{% extends "base.html" %}

{% block title %}
  Task Manager - Import
{% endblock %}

{% block css %}
  <style>
    input {width: 100%;}
  </style>
{% endblock %}

{% block h1 %}
  Task Manger - Import
{% endblock %}

{% block content %}
  {% if task_list %}
    <form action="{% url 'tasks:import-confirm' %}" method="post">
      {% csrf_token %}
      <table style="width:100%;">
        <caption><h2>{{ form.cleaned_data.iteration }}</h2></caption>
        <tr>
          <th width="20%">Ticket Number</th>
          <th width="80%">Summary</th>
        </tr>
        {% for number, summary in task_list %}
          <tr>
            <td><input type="text" name="task_number_{{ forloop.counter0 }}" value="{{ number }}"/></td>
            <td><input type="text" name="task_summary_{{ forloop.counter0 }}" value="{{ summary }}"/></td>
          </tr>
        {% endfor %}
        <input type="hidden" name="iteration" value="{{ form.cleaned_data.iteration }}" />
        <input type="hidden" name="planned_time" value="{{ form.cleaned_data.planned_time|default_if_none:'' }}" />
        <input type="hidden" name="tasks_count" value="{{ task_list|length }}"/>
        <button type="submit">Import Tasks</button>
      </table>
    </form>
  {% else %}
    <form action="." method="post">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Submit</button>
    </form>
  {% endif %}
{% endblock %}

tasks/templates/index.html
{% extends "base.html" %}

{% block title %}
  Task Manager - Index
{% endblock %}

{% block h1 %}
  Welcome to Task Manager!
{% endblock %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        {% if iterations %}
          <table class="table table-striped">
            <caption>Tasks Summary</caption>
            <tr>
              <th>Iteration</th>
              <th>Total Tasks Count</th>
              <th>Created At</th>
              <th>Planned Time</th>
            </tr>
            {% for iteration in iterations %}
              <tr>
                <td><a href="{% url 'tasks:list' iteration.name %}">{{ iteration.name }}</a></td>
                <td>{{ iteration.task_set.count }}</td>
                <td>{{ iteration.date_created }}</td>
                <td>{{ iteration.planned_time }}</td>
              </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>No Tasks!</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

tasks/templates/list.html
{% extends "base.html" %}
{% load link %}

{% block title %}
  Task Manager - {{ iteration.name }} Task List
{% endblock %}

{% block h1 %}
  Task Manager - {{ iteration.name }} Task List
{% endblock %}

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="btn-group btn-group-justified" role="group">
          <a class="btn btn-primary" role="button" href="{% url 'tasks:export' iteration.name %}">Export</a>
          <a class="btn btn-primary" role="button" href="{% url 'tasks:export' iteration.name %}?with_owner=true">Export With Owner</a>
          <a class="btn btn-primary" role="button" href="{% url 'tasks:add' iteration.name %}">Add Task</a>
          </div>
        </div>
      </div>
    <div class="row">
      <div class="col-md-12">
        <div class="h2">
          Total Planned Time: <span class="label label-default">{{ iteration.planned_time }}</span>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        {% with iteration.task_set.all as tasks %}
          {% if tasks %}
            <table class="sortable table table-striped">
              <thead>
                <tr>
                  <th>Ticket Number</th>
                  <th>Summary</th>
                  <th>
                    <a class="btn btn-info btn-xs" href="javascript:void(0);" onclick="showOwnersTime();"><em>Sum</em></a>
                    <a class="btn btn-info btn-xs" href="javascript:void(0);" onclick="showGroupedTasks();"><em>Group By</em></a>
                    Owner
                  </th>
                  <th><a class="btn btn-info btn-xs" href="javascript:void(0);" onclick="showSumTime();"><em>Sum</em></a> Estimated Hours</th>
                  <th>Need Code Review</th>
                  <th>Review Time</th>
                  <th>Frozen <em>(Exclude from estimation)</em></th>
                </tr>
              </thead>
              <tbody>
                {% for task in tasks %}
                  <tr data-task-id="{{ task.id }}">
                    <td>{{ task.ticket_id|bind_link }}</td>
                    <td class="editable" data-name="summary">{{ task.summary }}</td>
                    <td class="editable" data-type="owner-select" data-name="owner_id">{{ task.owner|default_if_none:"" }}</td>
                    <td class="editable" data-name="estimated_hours">{{ task.estimated_hours }}</td>
                    <td><input name="need_review" type="checkbox"{% if task.need_review %} checked="checked"{% endif %}></td>
                    <td class="editable" data-name="review_time">{{ task.review_time }}</td>
                    <td><input name="frozen" type="checkbox"{% if task.frozen %} checked="checked"{% endif %}></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            No Tasks.
          {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>

  <div class="modal fade" id="message-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block js %}
  <script>
    function showMessage(title, message) {
      $messageModal = $("#message-modal");
      $messageModal.find(".modal-title").html(title);
      $messageModal.find(".modal-body").html(message);
      $('#message-modal').modal('show');
    }
    var owner_select = '{{ owner_select|safe }}';
    function showOwnersTime() {
      var sum_url = "{% url 'tasks:owner-hours' iteration.name %}";
      $.get(sum_url, function(data) {
        var $messageList = $('<ul>').addClass('list-group');
        for (var owner in data) {
          var $line = $('<li>').addClass('list-group-item');
          $line.text(owner);
          var $hourBadge = $('<span>').addClass('badge').text(data[owner]);
          $line.append($hourBadge);
          $messageList.append($line);
        }
        showMessage("Owner Hours", $messageList);
      });
    }
    function showSumTime() {
      var sum_url = "{% url "tasks:total-hours" iteration.name %}";
      $.get(sum_url, function(data) {
        showMessage("Total Time", data);
      });
    }
    function showGroupedTasks() {
      var url = "{% url "tasks:tasks-by-owner" iteration.name %}";
      $.get(url, function(data) {
        $messageContainer = $('<div>');
        for (var owner in data) {
          var $dl = $('<dl>');
          $dl.append($('<dt>').text(owner));
          var $dd = $('<dd>');
          var $ul = $('<ul>').addClass("list-unstyled");
          tickets = data[owner];
          for (var i=0; i<tickets.length; i++) {
            var ticket = tickets[i];
            var ticket_id = ticket[0], need_review = ticket[1];
            var ticket_text = ticket_id.toString();
            if (need_review) {
              ticket_text += ' *';
            }
            $ul.append($('<li>').text(ticket_text));
          }
          $dd.append($ul);
          $dl.append($dd);
          $messageContainer.append($dl);
        }
        showMessage("Tasks Group By Owner", $messageContainer);
      });
    }
    $(function() {
      $('.editable:not([data-type="owner-select"])').editable('{% url "tasks:update" %}', {
        submit: 'OK',
        submitdata: function (value, settings) {
          var obj = {};
          var t = $(this);
          obj.task_id  = t.parent('tr').data('task-id');
          obj.name = t.data('name');
          return obj;
        }
      });
      $('.editable[data-type="owner-select"]').editable('{% url "tasks:update" %}', {
        submit: 'OK',
        data: owner_select,
        type: 'select',
        submitdata: function () {
          var obj = {};
          var t = $(this);
          obj.task_id  = t.parent('tr').data('task-id');
          obj.name = t.data('name');
          return obj;
        }
      });
      $('.sortable').sortable({
        items: '> tbody > *',
        stop: function(event, ui) {
          var update_order_url = '{% url "tasks:update-ordering" %}';
          var t = $(ui.item);
          var idx = t.parent().children().index(t);
          $.get(update_order_url, {task_id: t.data('task-id'), ordering: idx});
        }
      });
      $('[name=frozen]').change(function(){
        var freeze_url = '{% url "tasks:freeze" %}';
        var t = $(this);
        var frozen = t.prop('checked');
        $.get(freeze_url, {task_id: t.closest('tr').data('task-id'), frozen: frozen});
      });
      $('[name=need_review]').change(function(){
        var need_review_url = '{% url "tasks:need-review" %}';
        var t = $(this);
        var need_review = t.prop('checked');
        $.get(need_review_url, {task_id: t.closest('tr').data('task-id'), need_review: need_review});
      });
    });
  </script>
{% endblock %}